global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sentiment-mlops'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Alerting rules (optional)
rule_files:
  # - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Sentiment API monitoring
  - job_name: 'sentiment-api'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'sentiment-api'
          environment: 'development'
